name: smartmeter2mqtt Release

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - smartmeter2mqtt-v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: smartmeter2mqtt
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            docker_platform: linux/arm64
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            docker_platform: linux/amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@v2
        with:
          tool: cross

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          manifest_path: tools/smartmeter2mqtt/Cargo.toml
          bin: smartmeter2mqtt
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: mkdir release
      - run: tar -C release -xf smartmeter2mqtt-${{ matrix.target }}.tar.gz

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: release
          file: tools/smartmeter2mqtt/Containerfile
          platforms: ${{ matrix.docker_platform }}
          push: true
          tags: ghcr.io/m1cha/smartmeter/smartmeter2mqtt/${{ matrix.docker_platform }}:latest
